name: "Build and Push to GHCR"
on:
  push:
    branches: [main]

env:
  working-directroy: ./

jobs:
  GHCR:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build and Push Docker Image'
        run: |
            docker build ./ref-card-02 --tag ghcr.io/evanlueber/m324_devops:latest
            docker push ghcr.io/evanlueber/m324_devops:latest